from __future__ import annotations

import ast
import json
from typing import TYPE_CHECKING, Any, cast

import typer
import yaml

if TYPE_CHECKING:
    from pathlib import Path

DOC_FIELDS = ("summary", "complexity", "since", "function", "reply_schema")


MAX_LINE_WIDTH = 120
FOLDED_STYLE_THRESHOLD = 80
PARENT_COMMAND_POSITIONAL_INDEX = 2


class _DocDumper(yaml.SafeDumper):
    pass


def _str_representer(dumper: yaml.Dumper, value: str) -> yaml.ScalarNode:
    if "\n" in value:
        return dumper.represent_scalar("tag:yaml.org,2002:str", value, style="|")
    if len(value) > FOLDED_STYLE_THRESHOLD:
        return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=">")
    return dumper.represent_scalar("tag:yaml.org,2002:str", value)


_DocDumper.add_representer(str, _str_representer)


def _render_docstring(fields: dict[str, Any], indent: str) -> str:
    ordered = {key: fields[key] for key in DOC_FIELDS if key in fields}
    dumped = yaml.dump(
        ordered,
        Dumper=_DocDumper,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=max(MAX_LINE_WIDTH - len(indent) - 10, 40),
    ).rstrip("\n")
    body = "\n".join(f"{indent}{line}" if line else indent for line in dumped.splitlines())
    return f'{indent}"""\n{body}\n{indent}"""'


def _bytes_literal(node: ast.AST) -> bytes | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, bytes):
        return node.value
    return None


def _command_decorator_info(class_node: ast.ClassDef) -> tuple[bytes, bytes | None] | None:
    for decorator in class_node.decorator_list:
        call = decorator if isinstance(decorator, ast.Call) else None
        if call is None:
            continue
        func = call.func
        func_name = func.id if isinstance(func, ast.Name) else (func.attr if isinstance(func, ast.Attribute) else None)
        if func_name != "command":
            continue
        if not call.args:
            return None
        name = _bytes_literal(call.args[0])
        if name is None:
            return None
        parent: bytes | None = None
        if len(call.args) > PARENT_COMMAND_POSITIONAL_INDEX:
            parent = _bytes_literal(call.args[PARENT_COMMAND_POSITIONAL_INDEX])
        for kw in call.keywords:
            if kw.arg == "parent_command":
                parent = _bytes_literal(kw.value)
        return name, parent
    return None


def _valkey_json_path(valkey_dir: Path, name: bytes, parent: bytes | None) -> Path:
    stem = (parent.decode() + "-" + name.decode()) if parent else name.decode()
    return valkey_dir / f"{stem}.json"


def _extract_fields(valkey_json_path: Path) -> dict[str, Any]:
    data = json.loads(valkey_json_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or len(data) != 1:
        return {}
    body = next(iter(data.values()))
    if not isinstance(body, dict):
        return {}
    body_any = cast("dict[str, Any]", body)
    return {key: body_any[key] for key in DOC_FIELDS if key in body_any}


def _class_docstring_node(class_node: ast.ClassDef) -> tuple[ast.Expr, str] | None:
    if not class_node.body:
        return None
    first = class_node.body[0]
    if isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant) and isinstance(first.value.value, str):
        return first, first.value.value
    return None


def _docstring_is_autogenerated(text: str) -> bool:
    try:
        parsed = yaml.safe_load(text)
    except yaml.YAMLError:
        return False
    if not isinstance(parsed, dict):
        return False
    recognized = set(DOC_FIELDS) | {"reply_scheme"}
    return bool(parsed) and all(isinstance(k, str) and k in recognized for k in parsed)


def _line_offsets(source: str) -> list[int]:
    offsets = [0]
    for idx, ch in enumerate(source):
        if ch == "\n":
            offsets.append(idx + 1)
    return offsets


def _pos_to_offset(line_offsets: list[int], line: int, col: int) -> int:
    return line_offsets[line - 1] + col


def _node_end_offset(line_offsets: list[int], node: ast.stmt | ast.expr) -> int:
    if node.end_lineno is None or node.end_col_offset is None:
        raise ValueError(f"AST node {type(node).__name__} is missing end position information")
    return _pos_to_offset(line_offsets, node.end_lineno, node.end_col_offset)


def _process_file(source_path: Path, valkey_dir: Path, dry_run: bool) -> tuple[int, int, int]:
    source = source_path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return 0, 0, 0

    line_offsets = _line_offsets(source)
    edits: list[tuple[int, int, str]] = []  # (start_offset, end_offset, replacement_text)
    added = 0
    rewrapped = 0
    skipped_existing = 0

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        info = _command_decorator_info(node)
        if info is None:
            continue
        if not node.body:
            continue

        name, parent = info
        json_path = _valkey_json_path(valkey_dir, name, parent)
        if not json_path.exists():
            continue
        fields = _extract_fields(json_path)
        if not fields:
            continue

        body_indent = next(
            (stmt.col_offset for stmt in node.body[1:] if stmt.col_offset > node.col_offset),
            node.col_offset + 4,
        )
        indent = " " * body_indent

        docstring = _class_docstring_node(node)
        if docstring is None:
            first_stmt = node.body[0]
            text = _render_docstring(fields, indent)
            insert_at = _pos_to_offset(line_offsets, first_stmt.lineno, 0)
            edits.append((insert_at, insert_at, text + "\n"))
            added += 1
        else:
            docstring_node, existing_text = docstring
            if not _docstring_is_autogenerated(existing_text):
                skipped_existing += 1
                continue
            new_text = _render_docstring(fields, indent)
            start = _pos_to_offset(line_offsets, docstring_node.lineno, 0)
            end = _node_end_offset(line_offsets, docstring_node)
            if source[start:end] == new_text:
                continue
            edits.append((start, end, new_text))
            rewrapped += 1

    if edits and not dry_run:
        edits.sort(key=lambda item: item[0], reverse=True)
        new_source = source
        for start, end, text in edits:
            new_source = new_source[:start] + text + new_source[end:]
        source_path.write_text(new_source, encoding="utf-8")

    return added, rewrapped, skipped_existing


app = typer.Typer(add_completion=False)


@app.command()
def main(
    commands_dir: Path = typer.Argument(..., help="pyvalkey commands directory (contains *_commands.py)"),
    valkey_dir: Path = typer.Argument(..., help="valkey src/commands directory"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Scan only; do not modify any files"),
) -> None:
    """Inject YAML docstrings into pyvalkey command classes using fields from valkey JSON files."""
    commands_dir = commands_dir.resolve()
    valkey_dir = valkey_dir.resolve()
    if not commands_dir.is_dir() or not valkey_dir.is_dir():
        typer.echo("both directories must exist", err=True)
        raise typer.Exit(code=2)

    total_added = 0
    total_rewrapped = 0
    total_skipped = 0
    for source_path in sorted(commands_dir.glob("*_commands.py")):
        added, rewrapped, skipped = _process_file(source_path, valkey_dir, dry_run)
        if added or rewrapped or skipped:
            typer.echo(
                f"{source_path.name}: +{added} added, {rewrapped} rewrapped, {skipped} skipped (custom docstring)"
            )
        total_added += added
        total_rewrapped += rewrapped
        total_skipped += skipped

    verb = "would" if dry_run else ""
    typer.echo("")
    typer.echo(f"{verb} added {total_added}, rewrapped {total_rewrapped}, skipped {total_skipped}")


if __name__ == "__main__":
    app()
