from collections.abc import Callable, Iterable
from typing import Any

class _LuaObject:
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class _LuaTable(_LuaObject):
    def keys(self) -> Iterable[bytes | int]: ...
    def values(self) -> Iterable[Any]: ...
    def items(self) -> Iterable[tuple[bytes | int, Any]]: ...
    def set_readonly(self, enabled: bool = True) -> None: ...
    def is_readonly(self) -> bool: ...
    def __getitem__(self, key: str | int | bytes) -> Any: ...
    def __setitem__(self, key: str | int | bytes, value: Any) -> None: ...
    def __delitem__(self, key: str | int | bytes) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __delattr__(self, name: str) -> None: ...
    def __contains__(self, key: str | int | bytes) -> bool: ...
    def __iter__(self) -> Iterable[Any]: ...

class _LuaFunction(_LuaObject):
    def __call__(self, *args: Any) -> Any: ...
    def coroutine(self, *args: Any) -> _LuaCoroutineFunction: ...

class _LuaCoroutineFunction(_LuaObject):
    def __call__(self, *args: Any) -> Any: ...
    def send(self, value: Any = None) -> Any: ...

class LuaRuntime:
    def __init__(
        self,
        *,
        encoding: str | None = None,
        source_encoding: str | None = "UTF-8",
        unpack_returned_tuples: bool = False,
        overflow_handler: Callable[..., Any] | None = None,
        register_eval: bool = True,
        register_builtins: bool = True,
        attribute_filter: Callable[[Any, str, bool], bool] | None = None,
        attribute_handlers: tuple[Callable[..., Any] | None, Callable[..., Any] | None] | None = None,
    ) -> None: ...
    def eval(self, lua_code: bytes, *args: Any) -> Any: ...
    def execute(self, lua_code: bytes, *args: Any) -> Any: ...
    def compile(self, lua_code: bytes) -> _LuaFunction: ...
    def require(self, modulename: str) -> Any: ...
    def globals(self) -> _LuaTable: ...
    def table(self, *items: Any, **kwargs: Any) -> _LuaTable: ...
    def table_from(self, *args: Any, recursive: bool = False) -> _LuaTable: ...

class LuaError(Exception): ...
class LuaSyntaxError(LuaError): ...
class LuaMemoryError(LuaError, MemoryError): ...

def lua_type(obj: object) -> str | None: ...
def unpacks_lua_table(fn: Callable[..., Any]) -> Callable[..., Any]: ...
def unpacks_lua_table_method(fn: Callable[..., Any]) -> Callable[..., Any]: ...
